epochs: 2
global_batch_size: 8192
shuffle_buffer: 10
train_rows: 65536
trainval_rows: 8192
eval_rows: 65536
compression: "GZIP"
train_path: "gs://mgaiduk-us-central1/ratings/csv_gzip/part*"
validate_path: "gs://mgaiduk-us-central1/ratings_validate/csv_gzip/part*"
save_model_path: "gs://mgaiduk-us-central1/models/model1"
cycle_length: 8
dataset_features:
    userId:
        type: "string"
    movieId:
        type: "string"
    label:
        type: "int"
    timestamp:
        type: "int"
label: label
model:
    learning_rate: 0.01
    features:
        userId:
            hash: true
            vocab_size: 25000000
            embedding_dim: 16
            belongs_to: user
        movieId:
            hash: true
            vocab_size: 5000000
            embedding_dim: 16
            belongs_to: movie
